# Generated by Django 4.2.6 on 2024-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
