# Generated by Django 4.2.6 on 2024-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
