# Generated by Django 4.2.6 on 2024-01-19 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_verfiycontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerfiyContact',
            new_name='VerifyContact',
        ),
    ]
