# Generated by Django 4.2.6 on 2024-02-05 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0017_alter_realtor_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 5, 18, 19, 47, 207048)),
        ),
    ]
