# Generated by Django 4.2.6 on 2024-01-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='original_listing_person',
        ),
    ]
