# Generated by Django 4.2.6 on 2024-01-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_latitude_alter_listing_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lines', models.ManyToManyField(related_name='stations', to='listings.line')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='nearby_stations',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.station'),
        ),
    ]
