# Generated by Django 4.2.6 on 2024-02-05 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0008_listing_pred_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=11, max_digits=15)),
                ('radius', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
