# Generated by Django 4.2.6 on 2024-02-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_investmentpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentpreference',
            name='postcode',
            field=models.CharField(default='rm10 7nu', max_length=10),
            preserve_default=False,
        ),
    ]
