# Generated by Django 4.2.6 on 2024-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_investmentpreference_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True)),
            ],
        ),
    ]
